import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Users, User, Phone, Eye } from 'lucide-react';
import { useData } from '@/hooks/useData';
import { DocumentViewer } from '@/components/DocumentViewer';

export function AdminLeadsList({ leads, getStatusIcon, getStatusColor, getLatestRemark }) {
  const { getVLEs } = useData();
  const ALL_VLES = getVLEs();

  return (
    <div className="grid gap-4 sm:gap-6">
      {leads.length === 0 ? (
        <Card><CardContent className="text-center py-12"><Users className="mx-auto h-12 w-12 text-gray-400" /><h3 className="mt-4 text-lg font-medium">No leads yet</h3></CardContent></Card>
      ) : (
        leads.map(lead => (
          <Card key={lead.id} className="card-hover animate-fade-in">
            <CardHeader>
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center">
                <div className="mb-2 sm:mb-0">
                  <CardTitle className="text-md sm:text-lg">{lead.service_name}</CardTitle>
                  <CardDescription className="text-xs sm:text-sm">Lead ID: {lead.id}</CardDescription>
                </div>
                <Badge className={`${getStatusColor(lead.status)} flex items-center gap-1 text-xs px-2 py-1`}>
                  {getStatusIcon(lead.status)} {lead.status.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                </Badge>
              </div>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 sm:gap-4 text-xs sm:text-sm">
                <div className="flex items-center gap-2"><User className="h-4 w-4" /><span>{lead.customer_name}</span></div>
                <div className="flex items-center gap-2"><Phone className="h-4 w-4" /><span>{lead.customer_phone}</span></div>
                <div><span className="font-medium">Fee:</span> ₹{lead.fee}</div>
                <div><span className="font-medium">Generated by:</span> {ALL_VLES.find(v => v.id === lead.vle_id)?.name || 'N/A'}</div>
                <div><span className="font-medium">Created:</span> {new Date(lead.created_at).toLocaleDateString()}</div>
                <div>
                  <span className="font-medium">Documents:</span> {lead.documents?.length || 0}
                  <Dialog>
                    <DialogTrigger asChild><Button variant="link" size="sm" className="p-0 h-auto ml-1"><Eye className="h-3 w-3"/></Button></DialogTrigger>
                    <DialogContent>
                      <DialogHeader><DialogTitle>View Documents for {lead.service_name}</DialogTitle></DialogHeader>
                      <DocumentViewer documents={lead.documents} />
                    </DialogContent>
                  </Dialog>
                </div>
                {lead.assignedVleName !== 'N/A' && (<div><span className="font-medium">Assigned to:</span> {lead.assignedVleName}</div>)}
              </div>
              <p className="text-xs text-gray-500 mt-2"><span className="font-medium">Latest Remark:</span> {getLatestRemark(lead)}</p>
            </CardContent>
          </Card>
        ))
      )}
    </div>
  );
}